version: '3.5'

services:
  web-restful-api-db-service:
    container_name: "web-restful-api-db"
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: letmein
      POSTGRES_USER: root
      POSTGRES_DB: web-restful-api
